# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  configVars,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ../common/optional/cirdan-smb-shares.nix ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/NIXOS_SD";
    fsType = "ext4";
    options = [ "noatime" ];
  };
  fileSystems."/firmware" = {
    device = "/dev/disk/by-label/FIRMWARE";
    fsType = "vfat";
  };

  # Cirdan SMB mounts
  fileSystems."/mnt/cirdan/smb/Comics" = cirdanSmb.mainConfig "Comics";
  fileSystems."/mnt/cirdan/smb/Jellyfin" = cirdanSmb.mainConfig "Jellyfin";
  fileSystems."/mnt/cirdan/smb/NetBackup" = cirdanSmb.mainConfig "NetBackup";
  fileSystems."/mnt/cirdan/smb/Family_Data" = cirdanSmb.mainConfig "Family_Data";
  fileSystems."/mnt/cirdan/smb/data.dat" = cirdanSmb.secondaryConfig "data.dat";
  fileSystems."/mnt/cirdan/smb/syncthing" = cirdanSmb.ROSecondaryConfig "syncthing";

  # Swap
  swapDevices = [
    {
      device = "/swapfile";
      size = 1024;
    }
  ];

  powerManagement.cpuFreqGovernor = "ondemand";

  # Disable TPM2 support - Allows building on non-TPM2 systems
  boot.initrd.systemd.tpm2.enable = false;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
