# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # BIOS Updater through LVFS - Run `fwupdmgr update` to update firmware
  services.fwupd.enable = true;

  # Video Hardware
  hardware.graphics.extraPackages = with pkgs.rocmPackages; [
    clr
    clr.icd
    rocblas
    rpp
    pkgs.amdvlk
    pkgs.nvtopPackages.amd
  ];

  boot.initrd.enable = true;
  boot.supportedFilesystems = [ "btrfs" ];
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/prancing";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/prancing";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/prancing";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
    neededForBoot = true;
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-label/prancing";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/prancing";
    fsType = "btrfs";
    options = [
      "subvol=log"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4B93-0499";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
    neededForBoot = true;
  };

  fileSystems."/gaming/prancing" = {
    device = "/dev/disk/by-label/prancing";
    fsType = "btrfs";
    options = [
      "subvol=games"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
  };

  fileSystems."/etc/nixos" = {
    device = "/dev/disk/by-label/prancing";
    fsType = "btrfs";
    options = [
      "subvol=nixos-config"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
  };

  fileSystems."/gaming/pony" = {
    device = "/dev/disk/by-label/pony";
    fsType = "btrfs";
    options = [
      "subvol=games"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
  };

  fileSystems."/var/lib/ai-models" = {
    device = "/dev/disk/by-label/pony";
    fsType = "btrfs";
    options = [
      "subvol=ai-models"
      "compress=zstd"
      "noatime"
      "defaults"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-label/swap"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp191s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp192s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
