# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [ (modulesPath + "/virtualisation/amazon-image.nix") ];

  # Swap
  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 512; # in MB
    }
  ];

  # Not sure if this matters, see https://serverfault.com/questions/637102/what-is-the-difference-between-pv-and-hvm-virtualization-types-in-ec2
  ec2.hvm = true;

  # Mounting S3 bucket
  fileSystems."nocoolnamtom-com-pleroma" =
    let
      region = "us-west-2";
      iamRole = "ec2-use-s3-nocoolnamtom-com-pleroma";
    in
    {
      device = "nocoolnamtom-com-pleroma";
      mountPoint = "/mnt/s3mount";
      fsType = "fuse./run/current-system/sw/bin/s3fs";
      noCheck = true;
      options = [
        "_netdev"
        "rw"
        "allow_other"
        "use_path_request_style"
        "iam_role=${iamRole}"
        "url=https://s3-${region}.amazonaws.com"
        "endpoint=${region}"
        "use_cache=/tmp"
      ];
    };

  environment.systemPackages = with pkgs; [
    fuse
    s3fs
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
