# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  configVars,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/695982ba-f44d-4605-9026-6111de47a1a6";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "rw"
      "noatime"
      "discard=async"
      "compress-force=zstd"
      "space_cache=v2"
      "commit=120"
    ];
  };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/678b29b2-dd2d-4b2a-bd0a-98e6fb7e2c0a";

  # USB DAS - 4x 4TB SSDs in BTRFS RAID5
  # Decrypted by systemd-cryptsetup AFTER boot (not in initrd) to avoid USB enumeration delays
  # TPM2 auto-unlock with password fallback
  # To enroll TPM2 keys after first boot, run for each device:
  #   sudo systemd-cryptenroll --tpm2-device=auto /dev/disk/by-uuid/<UUID>
  environment.etc."crypttab".text = ''
    usb_das_1 UUID=df0adec1-e2b7-479f-befa-26af079b118c - tpm2-device=auto
    usb_das_2 UUID=272a11cd-61ee-4c35-87ac-7edde497359d - tpm2-device=auto
    usb_das_3 UUID=7a29e1e2-a0ae-40fc-8c43-1a1134df1d69 - tpm2-device=auto
    usb_das_4 UUID=4ca6a3ed-cc82-4184-bb6c-b726536745e5 - tpm2-device=auto
  '';

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/695982ba-f44d-4605-9026-6111de47a1a6";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "rw"
      "noatime"
      "discard=async"
      "compress-force=zstd"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/695982ba-f44d-4605-9026-6111de47a1a6";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "rw"
      "noatime"
      "discard=async"
      "compress-force=zstd"
      "space_cache=v2"
      "commit=120"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/695982ba-f44d-4605-9026-6111de47a1a6";
    fsType = "btrfs";
    options = [
      "subvol=persist"
      "rw"
      "noatime"
      "discard=async"
      "compress-force=zstd"
      "space_cache=v2"
      "commit=120"
    ];
    neededForBoot = true;
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/695982ba-f44d-4605-9026-6111de47a1a6";
    fsType = "btrfs";
    options = [
      "subvol=log"
      "rw"
      "noatime"
      "discard=async"
      "compress-force=zstd"
      "space_cache=v2"
      "commit=120"
    ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6EC5-7289";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/etc/nixos" = {
    device = "/dev/disk/by-uuid/695982ba-f44d-4605-9026-6111de47a1a6";
    fsType = "btrfs";
    options = [
      "subvol=nixos-config"
      "rw"
      "noatime"
      "discard=async"
      "compress-force=zstd"
      "space_cache=v2"
      "commit=120"
    ];
  };

  # USB DAS BTRFS RAID5 volume - mounts after decryption
  # Decrypted after boot by systemd-cryptsetup using /etc/crypttab
  # nofail + x-systemd.device-timeout ensure boot continues if drives aren't available
  # compress-force=zstd enables transparent compression for all files
  fileSystems."/arkenstone" = {
    device = "/dev/disk/by-uuid/64da11e3-1656-4d81-b3e6-656d60f4d5ed";
    fsType = "btrfs";
    options = [
      "nofail"
      "noatime"
      "compress-force=zstd"
      "space_cache=v2"
      "x-systemd.device-timeout=30"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/0dc2ec7e-20df-4225-a80a-9887468501fd"; }
  ];

  boot.initrd.systemd.services.rollback = {
    enable = config.environment.persistence."${configVars.persistFolder}".enable;
    description = "Rollback BTRFS root subvolume to a pristine state";
    wantedBy = [ "initrd.target" ];

    # LUKS/TPM process
    after = [ "systemd-cryptsetup@cryptroot.service" ];

    # Before mounting the system root (/sysroot) during the early boot process
    before = [ "sysroot.mount" ];

    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";
    script = ''
      mkdir -p /mnt

      # We first mount the BTRFS root to /mnt
      # so we can manipulate btrfs subvolumes.
      mount -o subvol=/ /dev/mapper/cryptroot /mnt

      # While we're tempted to just delete /root and create
      # a new snapshot from /root-blank, /root is already
      # populated at this point with a number of subvolumes,
      # which makes `btrfs subvolume delete` fail.
      # So, we remove them first.
      #
      # /root contains subvolumes:
      # - /root/var/lib/portables
      # - /root/var/lib/machines

      btrfs subvolume list -o /mnt/root |
        cut -f9 -d' ' |
        while read subvolume; do
          echo "deleting /$subvolume subvolume..."
          btrfs subvolume delete "/mnt/$subvolume"
        done &&
        echo "deleting /root subvolume..." &&
        btrfs subvolume delete /mnt/root
      echo "restoring blank /root subvolume..."
      btrfs subvolume snapshot /mnt/root-blank /mnt/root

      # Once we're done rolling back to a blank snapshot,
      # we can unmount /mnt and continue on the boot process.
      umount /mnt
    '';
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
