# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, configVars, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices."estel".device = "/dev/disk/by-uuid/bbf231eb-a21d-4036-916d-1957411f1075";

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/59072bfb-dce5-4624-b53a-1e02a24f695d";
      fsType = "btrfs";
      options = [
        "defaults"
        "compress-force=zstd"
        "noatime"
        "ssd"
        "subvol=root"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/59072bfb-dce5-4624-b53a-1e02a24f695d";
      fsType = "btrfs";
      options = [
        "defaults"
        "compress-force=zstd"
        "noatime"
        "ssd"
        "subvol=home"
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/59072bfb-dce5-4624-b53a-1e02a24f695d";
      fsType = "btrfs";
      options = [
        "defaults"
        "compress-force=zstd"
        "noatime"
        "ssd"
        "subvol=nix"
      ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/59072bfb-dce5-4624-b53a-1e02a24f695d";
      fsType = "btrfs";
      options = [
        "defaults"
        "compress-force=zstd"
        "noatime"
        "ssd"
        "subvol=persist"
      ];
      neededForBoot = true;
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/59072bfb-dce5-4624-b53a-1e02a24f695d";
      fsType = "btrfs";
      options = [
        "defaults"
        "compress-force=zstd"
        "noatime"
        "ssd"
        "subvol=nixos-config"
      ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/59072bfb-dce5-4624-b53a-1e02a24f695d";
      fsType = "btrfs";
      options = [
        "defaults"
        "compress-force=zstd"
        "noatime"
        "ssd"
        "subvol=log"
      ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D680-F6A9";
      fsType = "vfat";
      options = [
        "uid=0"
        "gid=0"
        "fmask=0077"
        "dmask=0077"
        # Above is to silence journalctl boot warning?
        "noatime"
        "nodiratime"
        "discard"
      ]; # Supposedly better for the SSD.
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/42683d7b-94cb-41d2-8985-616e72d32913"; }
    ];

  boot.initrd.systemd.services.rollback = {
    enable = config.environment.persistence."${configVars.persistFolder}".enable;
    description = "Rollback BTRFS root subvolume to a pristine state";
    wantedBy = ["initrd.target"];

    # LUKS/TPM process. 
    after = ["systemd-cryptsetup@estel.service"];

    # Before mounting the system root (/sysroot) during the early boot process
    before = ["sysroot.mount"];

    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";
    script = ''
      mkdir -p /mnt

      # We first mount the BTRFS root to /mnt
      # so we can manipulate btrfs subvolumes.
      mount -o subvol=/ /dev/mapper/estel /mnt

      # While we're tempted to just delete /root and create
      # a new snapshot from /root-blank, /root is already
      # populated at this point with a number of subvolumes,
      # which makes `btrfs subvolume delete` fail.
      # So, we remove them first.
      #
      # /root contains subvolumes:
      # - /root/var/lib/portables
      # - /root/var/lib/machines

      btrfs subvolume list -o /mnt/root |
        cut -f9 -d' ' |
        while read subvolume; do
          echo "deleting /$subvolume subvolume..."
          btrfs subvolume delete "/mnt/$subvolume"
        done &&
        echo "deleting /root subvolume..." &&
        btrfs subvolume delete /mnt/root
      echo "restoring blank /root subvolume..."
      btrfs subvolume snapshot /mnt/root-blank /mnt/root

      # Once we're done rolling back to a blank snapshot,
      # we can unmount /mnt and continue on the boot process.
      umount /mnt
    '';
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
