# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  configVars,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.luks.devices."root".device = "/dev/disk/by-partuuid/50870cda-00f6-4e1d-8791-9c5efc872e43";

  boot.initrd.availableKernelModules = [
    "ahci"
    "nvme"
    "rtsx_pci_sdmmc"
    "sd_mod"
    "usb_storage"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [
    "amdgpu" # pang11 has a Raedeon GPU
    "dm-snapshot"
  ];
  hardware.opengl.extraPackages = [ pkgs.rocmPackages.clr.icd ]; # ROCm for OpenCL for AMD GPUs
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # TODO Set up encrypted boot stuff
  # boot.initrd.luks.yubikeySupport = true;
  # boot.initrd.luks.devices."root".yubikey = {
  #   slot = 2;
  #   twoFactor = false; # We want to automatically unlock when key is present at boot
  #   storage = {
  #     # store yubikey identifier in the unencrypted boot partition => /boot/crypt-storage/default
  #     device = "/dev/disk/by-partuuid/c00b9f98-9e15-496b-9b9d-39f5e8a3ee19";
  #     fsType = "vfat";
  #     path = "/crypt-storage/default";
  #   };
  # };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partuuid/c00b9f98-9e15-496b-9b9d-39f5e8a3ee19";
    fsType = "vfat";
    neededForBoot = true; # Not necessary since it shouldn't be encrypted, but good to call it out anyways
    options = [
      "noatime"
      "nodiratime"
      "discard"
    ]; # Supposedly better for the SSD.
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      # "size=12G" # Size of root filesystem built in memory, default of 50% of RAM if not present
      "size=54G" # Size of root filesystem built in memory, default of 50% of RAM if not present
      "mode=755" # Needed for SSH to be happy!
      "uid=0" # Root owns base / directory
      "gid=0" # Root owns base / directory
    ];
    neededForBoot = true; # required
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [
      "defaults"
      "compress-force=zstd"
      "noatime"
      "ssd"
      "subvol=nix"
    ];
    neededForBoot = true; # required
  };

  fileSystems."${configVars.persistFolder}" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [
      "defaults"
      "compress-force=zstd"
      "noatime"
      "ssd"
      "subvol=persist"
    ];
    neededForBoot = true; # required
  };

  # Not mounting Home so that we use the persist and impermanence instead for home!
  # fileSystems."/home" =
  #   { device = "/dev/mapper/root";
  #     fsType = "btrfs";
  #     options = [ "defaults" "compress-force=zstd" "noatime" "ssd" "subvol=home" ];
  #   };

  fileSystems."/etc/nixos" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [
      "defaults"
      "compress-force=zstd"
      "noatime"
      "ssd"
      "subvol=nixos-config"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/a73eac3a-0293-4996-a4c5-7ada673bc4be";
      randomEncryption.enable = true;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
