# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  configVars,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

{
  imports = [
    inputs.nixos-avf.nixosModules.avf
  ];

  # Change default user
  avf.defaultUser = configVars.username;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
